[package]
name = "day08"
version = "0.1.0"
edition = "2024"

[dependencies]
num-integer = "0.1.46"
stephen_morris_utils = { path = "../stephen_morris_utils/" }
# stephen_morris_utils = { git = "https://github.com/SteveStyle/utils.git" }
