[package]
name = "day03"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = "0.2.19"
regex = "1.11.1"
stephen_morris_utils = { path = "../stephen_morris_utils/" }
# stephen_morris_utils = { git = "https://github.com/SteveStyle/utils.git" }
