#![allow(dead_code, unused)]
use stephen_morris_utils::timer;

const INPUT: &str = include_str!("input.txt");
#[allow(dead_code)]
const TESTINPUT: &str = "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............";

mod antinodes;

mod grid;

fn main() {
    println!("Hello, world!");
}
