[package]
name = "day24"
version = "0.1.0"
edition = "2024"


[profile.release]
lto = true

[dependencies]
itertools = "0.14.0"
num-traits = "0.2.19"
stephen_morris_utils = { path = "../stephen_morris_utils/" }
# stephen_morris_utils = { git = "https://github.com/SteveStyle/utils.git" }
